### ISSUE TITLE
Issue in Excel import with Empty Cell

### ISSUE THREAD

**Issue by anilmaskara** [paulk-k2dev/DataImporterServiceBroker#1]
The cell that doesn't contain any data are getting skipped and the very next cell that has data in the row is used as the value of the empty column.

Similar issue
https://stackoverflow.com/questions/36100011/c-sharp-open-xml-empty-cells-are-getting-skipped-while-getting-data-from-excel

**Comment by paulk-k2dev** [comment]
Thanks for the feedback - I've changed the way it gets cell data now.

**Comment by anilmaskara** [comment]
Thanks Paul for the fix, but Now getting  following error in case of empty cell "Object Reference not set to an instance of object " . I am using Excel Import Option.

**Comment by paulk-k2dev** [comment]
OK, that’s not good -

Is it possible to share you excel sheet so I can use that?

**Comment by paulk-k2dev** [comment]
@anilmaskara I've updated the release again to use the older version of the GetCellValue - it should be OK now if you get the latest release package.

Please let me know how you get on.

**Comment by anilmaskara** [comment]
@paulk-k2dev  Its works like a charm now. Thanks for fixing it  ...
