### ISSUE TITLE
Decimal Handling

### ISSUE THREAD

**Issue by aiftikhar** [paulk-k2dev/DataImporterServiceBroker#2]
The service broker seems to not handle decimal with a certain number of decimal spaces past the 10. If you enter a value past ten spaces in bulk insert it will throw an error and show failed upload, if you try and enter it in non bulk mode it will upload but it will show the rows with larger than 10 decimal spaces were skipped. In this example I have SQL column set as Decimal (38,10), and the smart object is set to decimal as well. If I change the SQL column type to NVARCHAR the bulk insert is flawless, but it inserts the values as e-notation when presented with 0.0913286992 is stored as 9.1328699200000002E-2. Have tested this with multiple values such as the ones listed below and seem to get this error.

-3833.447098972611
3.10017776462250
-3833.4470989758611
1.6640697503554
8.761330352548235
-20565.099999999589
0.0913286992 

I have attempted to alter the source code to add the decimal rounding if the decimal is more then 10 spaces, but it seems to throw and error with data type mismatch all together when I do that.

**Comment by paulk-k2dev** [comment]
After some investigation it was only failing on the row with 0.0913286992 as the value.  Excel was storing this as scientific notation so it was failing to upload to the SmartObjects decimal property.

I have changed the method that is used to format the values before they are uploaded to attempt to convert from the scientific notation to decimal in the case where the target SmartObject property is of type decimal.

FYI if you use the non bulk method it will indicate to you on completion of import which row numbers failed to import.
