### ISSUE TITLE
Decimal Notation

### ISSUE THREAD

**Issue by aiftikhar** [paulk-k2dev/DataImporterServiceBroker#3]
A data mismatch error is occurring in part of the excel file that I am trying to upload using this project. After digging into the data of the excel file using the Open XML SDK Productivity Tool, I sense the issue is related to the number of decimal spaces, The data seems to be stored as regular decimal within excel file. In this example I have SQL column set as Decimal (38,10), and the smart object is set to decimal as well when I try to do the upload in non-bulk it skips rows with decimal data such as below. I have attempted to upload this to just NVARCHAR columns and the data displayed in SQL shows the Excel Stored Value slightly altered as well, which confused me further.

Excel Cell Value Displayed:  66..1
Excel Formula Bar Display: 66.0999999999999
Excel Stored Value: 66.099999999999895 (Retrieved using Open XML Productivity Tool)
SQL NVARCHAR Value: 66.099999999999994

Other Number samples with errors:
70.540000076895006
65.900367800650006
70.010000365000005
292.66045576700003
64.260458756400005
64.739999999999995
66.096789675999994
65.069999343239993

Not sure if this should be logged as a bug or user error.

**Comment by paulk-k2dev** [comment]
The precision of the decimal that you are storing is lower than the number of decimal places in the column in the excel spreadsheet so that value is getting rounded up.

Set the column to DECIMAL(38,15) and see how you go.

**Comment by aiftikhar** [comment]
I have updated the columns in MS SQL 2014 as suggested. I also updated the setting for the SQL Service Instance Max decimal value as well (max allowed is 29)  to 29,29), But I am still getting the same error.

**Comment by paulk-k2dev** [comment]
https://learn.microsoft.com/en-US/office/troubleshoot/excel/last-digits-changed-to-zeros - there is a limit on the number of digits.

What I have done in the attached spreadsheet [Book1-Formatted.xlsx](https://github.com/paulk-k2dev/DataImporterServiceBroker/files/11026055/Book1-Formatted.xlsx) is format the columns to be text as per the above article.

I have then set the target database table decimal column value to be decimal(29,20) (and refreshed the service instance)

And then ran the data  import console application, the data in the SDFQ5 column has imported to the 20th decimal place:

![image](https://user-images.githubusercontent.com/71258039/226549148-f510f167-73b2-4edf-b03e-49779fb19618.png)

**Comment by aiftikhar** [comment]
Thank you for your feedback, I owe to a pot of a coffee at the very least! This has fixed the issue and has worked perfectly as expected. I will need to make sure that the template the user's use has the field setup as suggested.
